services:
  - type: web
    name: realbook-excel-upload
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: REALBOOKS_USERNAME
        sync: false
      - key: REALBOOKS_PASSWORD
        sync: false
